# Generated by Django 3.0.14 on 2023-03-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focusapp', '0003_userprofilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out_for_delivery', 'Out_for_delivery'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Refund', 'Refund')], default='Pending', max_length=30),
        ),
    ]
